runtime: nodejs16

env: standard
instance_class: F1
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 500ms
  max_pending_latency: automatic
  max_instances: 2
handlers:
  - url: /.*
    script: auto
    secure: always

env_variables:
